# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\"\x11\n\x0fGetTermsRequest\"1\n\x10GetTermsResponse\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term\"!\n\x0eGetTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"Q\n\x0fGetTermResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1c\n\x04term\x18\x02 \x01(\x0b\x32\x0e.glossary.Term\x12\x0f\n\x07message\x18\x03 \x01(\t\"6\n\x0e\x41\x64\x64TermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"3\n\x0f\x41\x64\x64TermResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"9\n\x11UpdateTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"6\n\x12UpdateTermResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x11\x44\x65leteTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"6\n\x12\x44\x65leteTermResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\x04Term\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2\xe6\x02\n\x0fGlossaryService\x12\x41\n\x08GetTerms\x12\x19.glossary.GetTermsRequest\x1a\x1a.glossary.GetTermsResponse\x12>\n\x07GetTerm\x12\x18.glossary.GetTermRequest\x1a\x19.glossary.GetTermResponse\x12>\n\x07\x41\x64\x64Term\x12\x18.glossary.AddTermRequest\x1a\x19.glossary.AddTermResponse\x12G\n\nUpdateTerm\x12\x1b.glossary.UpdateTermRequest\x1a\x1c.glossary.UpdateTermResponse\x12G\n\nDeleteTerm\x12\x1b.glossary.DeleteTermRequest\x1a\x1c.glossary.DeleteTermResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTERMSREQUEST']._serialized_start=28
  _globals['_GETTERMSREQUEST']._serialized_end=45
  _globals['_GETTERMSRESPONSE']._serialized_start=47
  _globals['_GETTERMSRESPONSE']._serialized_end=96
  _globals['_GETTERMREQUEST']._serialized_start=98
  _globals['_GETTERMREQUEST']._serialized_end=131
  _globals['_GETTERMRESPONSE']._serialized_start=133
  _globals['_GETTERMRESPONSE']._serialized_end=214
  _globals['_ADDTERMREQUEST']._serialized_start=216
  _globals['_ADDTERMREQUEST']._serialized_end=270
  _globals['_ADDTERMRESPONSE']._serialized_start=272
  _globals['_ADDTERMRESPONSE']._serialized_end=323
  _globals['_UPDATETERMREQUEST']._serialized_start=325
  _globals['_UPDATETERMREQUEST']._serialized_end=382
  _globals['_UPDATETERMRESPONSE']._serialized_start=384
  _globals['_UPDATETERMRESPONSE']._serialized_end=438
  _globals['_DELETETERMREQUEST']._serialized_start=440
  _globals['_DELETETERMREQUEST']._serialized_end=476
  _globals['_DELETETERMRESPONSE']._serialized_start=478
  _globals['_DELETETERMRESPONSE']._serialized_end=532
  _globals['_TERM']._serialized_start=534
  _globals['_TERM']._serialized_end=578
  _globals['_GLOSSARYSERVICE']._serialized_start=581
  _globals['_GLOSSARYSERVICE']._serialized_end=939
# @@protoc_insertion_point(module_scope)
